service: adminator-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-southeast-2
  environment:
    tableName: ${self:custom.tableName}

custom:
  tableName: 'users-table-${sls:stage}'

plugins:
  - serverless-offline

functions:
  hello:
    handler: testhandler/testhandler.hello
    events:
      - http:
          path: /
          method: get

  loginTasty:
    handler: lambda-functions/loginTasty/index.handler
    events:
      - http:
          path: loginTasty
          method: post
          cors: true
